package routines.test;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

import routines.JobUtil;

public class TestJobUtil {
	
	@Test
	public void testUpdateJvmSettingsInJobRunScriptContent() {
		String sciptContent = "#!/bin/sh\n"
			    + "cd `dirname $0`\n"
			    + "ROOT_PATH=`pwd`\n"
			    + "java -Xms256M -Xmx16G -cp .:../lib/routines.jar:../lib/commons-lang-2.6.jar:../lib/commons-collections-3.2.2.jar:../lib/commons-logging-1.1.1.jar:../lib/commons-pool2-2.4.2.jar:../lib/log4j-1.2.16.jar:../lib/activation.jar:../lib/mail-1.4.jar:../lib/log4j-1.2.15.jar:../lib/dom4j-1.6.1.jar:../lib/bcprov-jdk15on-1.52.jar:../lib/jasperreports-functions-6.7.0.jar:../lib/jasperreports-fonts-6.0.0.jar:../lib/commons-logging-1.2.jar:../lib/xmlbeans-2.6.0.jar:../lib/groovy-2.4.11.jar:../lib/cimt-talendcomp-jobinstance-7.3.jar:../lib/jlo-talendcomp-jasperreportexec-4.1.jar:../lib/spring-core-3.2.4.RELEASE.jar:../lib/commons-compress-1.10.jar:../lib/json-simple-1.1.jar:../lib/cimt-talendcomp-jasperservrepo-2.3.jar:../lib/jasperreports-6.7.0.jar:../lib/joda-time-2.9.9.jar:../lib/serializer-2.7.2.jar:../lib/talendzip.jar:../lib/castor-core-1.3.3.jar:../lib/cimt-talendcomp-connectionpool-2.6.jar:../lib/checkArchive.jar:../lib/postgresql-9.4-1201.jdbc41.jar:../lib/gelfj-1.1.16.jar:../lib/poi-3.17.jar:../lib/advancedPersistentLookupLib-1.0.jar:../lib/jboss-serialization.jar:../lib/commons-digester-2.1.jar:../lib/jlo-talendcomp-excel-11.0.jar:../lib/commons-io-1.3.2.jar:../lib/icu4j-57.1.jar:../lib/itext-2.1.7.js6.jar:../lib/commons-compress-1.9.jar:../lib/artist-report-customizer-1.1.jar:../lib/commons-dbcp2-2.1.1.jar:../lib/xalan-2.7.2.jar:../lib/commons-beanutils-1.9.3.jar:../lib/bctsp-jdk16-1.46.jar:../lib/spring-beans-3.2.4.RELEASE.jar:../lib/zip4j_1.3.1.jar:../lib/commons-codec-1.10.jar:../lib/curvesapi-1.04.jar:../lib/castor-xml-1.3.3.jar:../lib/poi-ooxml-schemas-3.17.jar:../lib/ecj-4.4.2.jar:../lib/jackson-databind-2.9.5.jar:../lib/bcprov-jdk16-1.46.jar:../lib/commons-collections4-4.1.jar:../lib/poi-ooxml-3.17.jar:../lib/jcommon-1.0.23.jar:../lib/thashfile.jar:../lib/jfreechart-1.0.19.jar:../lib/pdf-renderer-1.0.5.jar:../lib/talendcsv.jar:../lib/trove.jar:../lib/talend_file_enhanced_20070724.jar:../lib/filecopy.jar:./dwh_vts_vendor_report_provide_as_zip_4_2.jar:./dwh_vts_vendor_report_excel__tt_one_vendor_0_1.jar:./dwh_vts_vendor_report_excel__vc_one_vendor_0_1.jar:./dwh_vts_vendor_report_provide_as_zip__one_vendor_3_0.jar:./dwh_vts_vendor_report_pdf__tt_one_vendor_2_1.jar:./dwh_vts_vendor_report_pdf__vc_one_vendor_en_2_1.jar:./dwh_vts_vendor_report_excel__vc_one_vendor_en_0_1.jar:./dwh_vts_vendor_report_pdf__vc_one_vendor_2_1.jar:./dwh_vts_vendor_report_pdf__tt_one_vendor_en_1_2.jar:./dwh_vts_vendor_report_excel__tt_one_vendor_en_0_1.jar: vts_and_dwh.dwh_vts_vendor_report_provide_as_zip_4_2.dwh_vts_vendor_report_provide_as_zip --context=Default \"$@\"";
		String newSettings = "-Xmx24G -server";
		String expectedSciptContent = "#!/bin/sh\n"
			    + "cd `dirname $0`\n"
			    + "ROOT_PATH=`pwd`\n"
			    + "java -Xmx24G -server -cp .:../lib/routines.jar:../lib/commons-lang-2.6.jar:../lib/commons-collections-3.2.2.jar:../lib/commons-logging-1.1.1.jar:../lib/commons-pool2-2.4.2.jar:../lib/log4j-1.2.16.jar:../lib/activation.jar:../lib/mail-1.4.jar:../lib/log4j-1.2.15.jar:../lib/dom4j-1.6.1.jar:../lib/bcprov-jdk15on-1.52.jar:../lib/jasperreports-functions-6.7.0.jar:../lib/jasperreports-fonts-6.0.0.jar:../lib/commons-logging-1.2.jar:../lib/xmlbeans-2.6.0.jar:../lib/groovy-2.4.11.jar:../lib/cimt-talendcomp-jobinstance-7.3.jar:../lib/jlo-talendcomp-jasperreportexec-4.1.jar:../lib/spring-core-3.2.4.RELEASE.jar:../lib/commons-compress-1.10.jar:../lib/json-simple-1.1.jar:../lib/cimt-talendcomp-jasperservrepo-2.3.jar:../lib/jasperreports-6.7.0.jar:../lib/joda-time-2.9.9.jar:../lib/serializer-2.7.2.jar:../lib/talendzip.jar:../lib/castor-core-1.3.3.jar:../lib/cimt-talendcomp-connectionpool-2.6.jar:../lib/checkArchive.jar:../lib/postgresql-9.4-1201.jdbc41.jar:../lib/gelfj-1.1.16.jar:../lib/poi-3.17.jar:../lib/advancedPersistentLookupLib-1.0.jar:../lib/jboss-serialization.jar:../lib/commons-digester-2.1.jar:../lib/jlo-talendcomp-excel-11.0.jar:../lib/commons-io-1.3.2.jar:../lib/icu4j-57.1.jar:../lib/itext-2.1.7.js6.jar:../lib/commons-compress-1.9.jar:../lib/artist-report-customizer-1.1.jar:../lib/commons-dbcp2-2.1.1.jar:../lib/xalan-2.7.2.jar:../lib/commons-beanutils-1.9.3.jar:../lib/bctsp-jdk16-1.46.jar:../lib/spring-beans-3.2.4.RELEASE.jar:../lib/zip4j_1.3.1.jar:../lib/commons-codec-1.10.jar:../lib/curvesapi-1.04.jar:../lib/castor-xml-1.3.3.jar:../lib/poi-ooxml-schemas-3.17.jar:../lib/ecj-4.4.2.jar:../lib/jackson-databind-2.9.5.jar:../lib/bcprov-jdk16-1.46.jar:../lib/commons-collections4-4.1.jar:../lib/poi-ooxml-3.17.jar:../lib/jcommon-1.0.23.jar:../lib/thashfile.jar:../lib/jfreechart-1.0.19.jar:../lib/pdf-renderer-1.0.5.jar:../lib/talendcsv.jar:../lib/trove.jar:../lib/talend_file_enhanced_20070724.jar:../lib/filecopy.jar:./dwh_vts_vendor_report_provide_as_zip_4_2.jar:./dwh_vts_vendor_report_excel__tt_one_vendor_0_1.jar:./dwh_vts_vendor_report_excel__vc_one_vendor_0_1.jar:./dwh_vts_vendor_report_provide_as_zip__one_vendor_3_0.jar:./dwh_vts_vendor_report_pdf__tt_one_vendor_2_1.jar:./dwh_vts_vendor_report_pdf__vc_one_vendor_en_2_1.jar:./dwh_vts_vendor_report_excel__vc_one_vendor_en_0_1.jar:./dwh_vts_vendor_report_pdf__vc_one_vendor_2_1.jar:./dwh_vts_vendor_report_pdf__tt_one_vendor_en_1_2.jar:./dwh_vts_vendor_report_excel__tt_one_vendor_en_0_1.jar: vts_and_dwh.dwh_vts_vendor_report_provide_as_zip_4_2.dwh_vts_vendor_report_provide_as_zip --context=Default \"$@\"";
		String actualScriptContent = JobUtil.updateJvmSettingsInJobRunScriptContent(sciptContent, newSettings);
		assertEquals("Script content incorrect", expectedSciptContent, actualScriptContent);
	}

}
